services:
  nginx:
    build:
      context: ./nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - react-build:/app/dist
    environment:
      USER_SERVICE_ADDR: user-service:3001
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - user-service
      - frontend
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail --insecure https://localhost/health-check || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 3
    command: /app/start.sh
    
  frontend:
    build:
      context: ./frontend
    volumes:
      - react-build:/app/dist
    entrypoint: ["sh", "-c", "npm run build && exit 0"]

  user-service:
    build:
      context: ./user-service
    container_name: user-service-backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - user-service-mongo
    volumes:
      - ./user-service:/app
      - /app/node_modules

  user-service-mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  react-build: