version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    container_name: user-service-backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - user-service-mongo
    volumes:
      - ./user-service:/app
      - /app/node_modules

  user-service-mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
